force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template of object to which we need to send email</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NT-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store email address to whom email will be send</description>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <description>Field to store email template name</description>
    <label>Email Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <description>field to store status of email notification</description>
    <label>Notification Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Field to store Id of record to which email should go</description>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Trigger_Date__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Date__c</fullName>
    <formula>DATEVALUE(Trigger_DateTime__c  )</formula>
    <label>Trigger Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Trigger_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Trigger_DateTime__c</fullName>
    <description>Field to store the triggering date time of email</description>
    <label>Trigger DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EmailBatch.cls
/**********************************************************************************************
@Description: Batch to send reminder email to user
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public class EmailBatch implements Database.Batchable<sObject>
, Database.AllowsCallouts
, Database.Stateful {
    
    
    List<Notification__c> lstNotificationToUpdate;
    transient List<Messaging.SingleEmailMessage> lstEmails;
    
    public Database.QueryLocator start(Database.BatchableContext batchContext) {
        return Database.getQueryLocator([SELECT 
                                         Id
                                         , Name
                                         , Trigger_DateTime__c
                                         , Email_Type__c
                                         , Notification_Status__c
                                         , Email__c
                                         , RecordId__c
                                         FROM 
                                         Notification__c
                                         WHERE  
                                         Trigger_Date__c = TODAY
                                         AND 
                                         Notification_Status__c = ''] ); 
        
    }
    //@description: Code we will send batch emails                                                
    public void execute(Database.BatchableContext batchContext, List<Notification__c> scope){
        if( !scope.isEmpty() && scope.size() > 0  ) {
            lstNotificationToUpdate = new List<Notification__c>();
            lstEmails = new List<Messaging.SingleEmailMessage>();
            EmailMessageService.EmailMessageWrapper objEmailMessageWrapper = new EmailMessageService.EmailMessageWrapper();
            EmailMessageService objEmailMessageService = new EmailMessageService();
            
            for( Notification__c objNotification : scope ) {
                objEmailMessageWrapper = objEmailMessageService.sendmail( objNotification );
                if( !objEmailMessageWrapper.lstNotificationToUpdate.isEmpty() ) {
                    lstNotificationToUpdate.addAll(objEmailMessageWrapper.lstNotificationToUpdate);
                }
                if( !objEmailMessageWrapper.lstEmails.isEmpty() ) {
                    lstEmails.addAll(objEmailMessageWrapper.lstEmails);
                }
            }
            if(!Test.isRunningTest()) {
                Messaging.sendEmail(lstEmails);
            }
            
            //@description: Update call count on calling list
            if( !lstNotificationToUpdate.isEmpty() ) {
                update lstNotificationToUpdate;
            }
        }
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}