force-app/main/default/objects/Pending_Registrations__c/Pending_Registrations__c.object-meta.xml
<CustomObject>
    <label>Pending Registrations</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Pending Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pending_Registrations__c/fields/Nick_Name__c.field-meta.xml
<CustomField>
    <fullName>Nick_Name__c</fullName>
    <label>Nick Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Other_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Institution_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Institution Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select record of type Institution Master</errorMessage>
        <filterItems>
            <field>Master_Configuration__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institution Master</value>
        </filterItems>
        <infoMessage>You can only select record of type Institution Master</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Configuration__c</referenceTo>
    <relationshipLabel>Pending Registrations</relationshipLabel>
    <relationshipName>Pending_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Sur_Name__c.field-meta.xml
<CustomField>
    <fullName>Sur_Name__c</fullName>
    <label>Sur Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PendingRegistrationController.cls
/**********************************************************************************************
@Description: An apex page controller that exposes the Pending Registrations functionality
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public with sharing class PendingRegistrationController {
    
    //@Description: This method used to get The Registered User List with pending Status
    @AuraEnabled
    public static List <Pending_Registrations__c> fetchPendingUsers() {
        List<Pending_Registrations__c> pendinguserList = new List<Pending_Registrations__c>();
        if (Schema.sObjectType.Pending_Registrations__c.isAccessible()){
        pendinguserList = [SELECT Id, Name, Email__c,                                      
                   First_Name__c, Nick_Name__c, Password__c, Status__c,Sur_Name__c,Username__c,Other_Institution_Name__c from Pending_Registrations__c where Status__c=:ZOE_Constant.PENDING ];
        }
            return pendinguserList;
    }
    
    //@Description: This method used to Apperove the Registered User
    @AuraEnabled
    public static List <Pending_Registrations__c> approveUser(List<Pending_Registrations__c> pendinguserList ) {
        List<Pending_Registrations__c> lstPend = new List<Pending_Registrations__c>();
        //@Description: it's okay if password is null - we'll send the user a random password in that case
        try {
            for(Pending_Registrations__c pendingUser:pendinguserList){
             if(Schema.sObjectType.Pending_Registrations__c.fields.Status__c.isUpdateable())
                pendingUser.Status__c=ZOE_Constant.APPROVED;
             lstPend.add(pendingUser);
            }
            if (Schema.sObjectType.Pending_Registrations__c.isUpdateable()){
                   update lstPend;
            }    
            return fetchPendingUsers();
        }catch (Exception e) {
            throw new AuraHandledException( e.getMessage());    
        }
    }
    //@Description: This method used to Reject the Registered User
    @AuraEnabled
    public static String rejectUser(List<Pending_Registrations__c> pendinguserList ) {
        //@Description: it's okay if password is null - we'll send the user a random password in that case
        try {
            for(Pending_Registrations__c pendingUser:pendinguserList){
                   if(Schema.sObjectType.Pending_Registrations__c.fields.Status__c.isUpdateable())
                pendingUser.Status__c=ZOE_Constant.REJECTED;
            }
            if (Schema.sObjectType.Pending_Registrations__c.isUpdateable()){
            update pendinguserList;
            }
            return ZOE_Constant.SUCCESS;
        }catch (Exception e) {
            throw new AuraHandledException( e.getMessage());    
        }
    }
}