force-app/main/default/objects/Feature_Usage__c/Feature_Usage__c.object-meta.xml
<CustomObject>
    <label>Feature Usage</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Feature Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Usage__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z-Kit Calculator</fullName>
            </value>
            <value>
                <fullName>Virtual Assistant</fullName>
            </value>
            <value>
                <fullName>Lab Tracker</fullName>
            </value>
            <value>
                <fullName>Infusion Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feature_Usage__c/fields/Used_By__c.field-meta.xml
<CustomField>
    <fullName>Used_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Used By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Feature_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeatureUsage.cls
/**********************************************************************************************
@Description: An apex page controller that exposes the Feature Usage functionality
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public with sharing class FeatureUsage {
    //@Description: This method used insert Feature Usage details
    @AuraEnabled
    public static void insertFeatureUsage(String functionality) {
    
            String currentUser=UserInfo.getUserId();
            Feature_Usage__c feature=new Feature_Usage__c();
            feature.Functionality__c= functionality;
            feature.Used_By__c=currentUser;
            if (Schema.sObjectType.Feature_Usage__c.isCreateable()){
            insert feature;            
            
            }
        
    }
}