force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit_Log</label>
    <nameField>
        <displayFormat>AUD-{0000000}</displayFormat>
        <label>Audit_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit_Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Nombre de la Institución</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/Pending_Registrations__c.object-meta.xml
<CustomObject>
    <label>Pending Registrations</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Pending Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pending_Registrations__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Matricula__c.field-meta.xml
<CustomField>
    <fullName>Matricula__c</fullName>
    <label>Matricula</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Nick_Name__c.field-meta.xml
<CustomField>
    <fullName>Nick_Name__c</fullName>
    <label>Nick Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>Profession</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Sur_Name__c.field-meta.xml
<CustomField>
    <fullName>Sur_Name__c</fullName>
    <label>Sur Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pending_Registrations__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZOE_LoginCntrl.cls
/**********************************************************************************************
@Description: An apex page controller that exposes the User login functionality
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public with sharing class ZOE_LoginCntrl {
    //@Description:This Method used to get Institution Name from Master Configurations
    @AuraEnabled
    public static List<String> getInstitutionName() {
        
        try {
            List<String> instituteNames=new List<String>();            
            if(Schema.sObjectType.Master_Configuration__c.isAccessible()){
            List<Master_Configuration__c> institutionCenters=[select Id,Institution_Name__c from Master_Configuration__c where RecordType.Name=:ZOE_Constant.MC_INSTITUTIONS];
             for(Master_Configuration__c masterConfig:institutionCenters){
                instituteNames.add(masterConfig.Institution_Name__c);
            }
        }
            return instituteNames;
        }
        catch (Exception e) {
            throw new AuraHandledException( e.getMessage());    
        }
    }
    
    //@Description:This Method used to validate login details and redirct to landing page
    @AuraEnabled
    public static String login(String username , String password) {
        
        try {
            String startUrl = Label.siteurl+'zeolandingpage';
            ApexPages.PageReference pageRef = Site.login(username, password, startUrl);
            return pageRef.getUrl();
        }
        catch (Exception e) {
            throw new AuraHandledException( e.getMessage());    
        }
    }
    
    //This Method used for forgot password functionality
    @AuraEnabled
    public static String forgotPassword(String strusername ) {
        try {
            List<User> existingPortalUsers;
            if (Schema.sObjectType.User.isAccessible())
              existingPortalUsers= [select id,Username,IsActive from User where Username =: strusername and IsActive = true ];
                 if(existingPortalUsers.size()>0){ 
               boolean success = Site.forgotPassword(strusername);
                if (success) {  
                 return 'success';
            }else {
                return 'failure';
            }
            }else{
                return 'fail';
            } 
        }
            catch (Exception e) {
          
            throw new AuraHandledException( e.getMessage()); 
        }
         
    }
   
    //@Description:This Method used to Register New User
  
    @AuraEnabled
    public static String registerUser(String primaryName,
                                      String primarySurname,
                                      String email,
                                      String profession,
                                      String matricula,
                                      List<String> institutionList) {
                                          String firstname=null;
                                          String surname=null;
                                          try {
                                             String institutions = String.join( institutionList, ', ' ); 
                                              Pending_Registrations__c objPendingReg=new Pending_Registrations__c();
                                              firstname = primaryName.replaceAll( '\\s+', '');
                                              surname = primarySurname.replaceAll( '\\s+', '');
                                              String username=firstname+surname+generateRandomString(5)+'@zolgensma.com';
                                               objPendingReg.Username__c = username ;
                                              objPendingReg.Email__c = email;
                                              objPendingReg.Nick_Name__c = firstname.substring(0,2)+surname.substring(0,2);
                                              objPendingReg.First_Name__c= firstname;
                                              objPendingReg.Sur_Name__c= surname;
                                              objPendingReg.Profession__c=profession;
                                              objPendingReg.Matricula__c=matricula;
                                              objPendingReg.Institution__c=institutions;
                                              objPendingReg.Status__c=ZOE_Constant.PENDING;
                                              if (Schema.sObjectType.Pending_Registrations__c.isCreateable()){
                                              insert objPendingReg;
                                              }    
                                               Audit_Log__c objAudit_Log = MasterConfigController.createAuditRecord(objPendingReg.Id,JSON.serialize(objPendingReg),'Pending_Registrations__c','Insert');
                                              if (Schema.sObjectType.Audit_Log__c.isCreateable()){
                                              insert objAudit_Log;
                                              }
                                              return ZOE_Constant.SUCCESS;
                                          }
                                          catch (Exception e) {
                                              throw new AuraHandledException( e.getMessage());    
                                          }
                                      }
    
    //@Description:This Method used to random string by length
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}