force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit_Log</label>
    <nameField>
        <displayFormat>AUD-{0000000}</displayFormat>
        <label>Audit_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit_Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Actividad del calendario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_desc__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_desc__c</fullName>
    <label>Calendario Actividad Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_duration__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_duration__c</fullName>
    <label>Duración de la actividad del calendario</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_Duration_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Duration_Type__c</fullName>
    <label>Calendario Actividad Duración Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Plantilla de correo electrónico de calen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infusion day</fullName>
            </value>
            <value>
                <fullName>New case generated</fullName>
            </value>
            <value>
                <fullName>Pre infusion</fullName>
            </value>
            <value>
                <fullName>Post Infusion week1</fullName>
            </value>
            <value>
                <fullName>Post Infusion week2</fullName>
            </value>
            <value>
                <fullName>Post Infusion week3</fullName>
            </value>
            <value>
                <fullName>Post Infusion week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/First_Notification__c.field-meta.xml
<CustomField>
    <fullName>First_Notification__c</fullName>
    <label>Primera Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Second_Notification__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification__c</fullName>
    <label>Segunda Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template of object to which we need to send email</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NT-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Field to store Id of record to which email should go</description>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/User_Calendar__c.object-meta.xml
<CustomObject>
    <label>User Calendar</label>
    <nameField>
        <label>User Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Calendar Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Date__c</fullName>
    <label>Calendar Activity Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Day__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Day__c</fullName>
    <label>Calendar Day</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Calendar_email_template</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Week__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Week__c</fullName>
    <label>Calendar Week</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event_Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/First_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Date__c</fullName>
    <label>First_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Second_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Date__c</fullName>
    <label>Second_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/User_Infusion_Date_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Infusion_Date_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Infusion Dates</label>
    <referenceTo>User_Infusion_Dates__c</referenceTo>
    <relationshipLabel>User Calendar</relationshipLabel>
    <relationshipName>User_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/User_Infusion_Dates__c.object-meta.xml
<CustomObject>
    <label>User Infusion Dates</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Infusion_Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Infusion_Dates__c/fields/Infusion_Date__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Date__c</fullName>
    <label>Infusion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/recordTypes/Infusion_Date.recordType-meta.xml
<RecordType>
    <fullName>Infusion_Date</fullName>
    <active>true</active>
    <label>Infusion Date</label>
</RecordType>

force-app/main/default/classes/CalendarActivtiesTriggerHelper.cls
/**********************************************************************************************
@Description: This Apex Trigger Helper is for inserting the activvities based on the infusion date.
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History 
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public with sharing class CalendarActivtiesTriggerHelper {
    public static void afterInsertHelper( list<User_Infusion_Dates__c>  infusion_DateList){
			if (Trigger.isUpdate) {
                List< User_Calendar__c > lstUserCalendar = new List<User_Calendar__c>();
                List< Notification__c > lstNotifications = new List<Notification__c>();
                if (Schema.sObjectType.User_Calendar__c.isAccessible()){
                lstUserCalendar =  [SELECT Id,Name,Event_Type__c FROM User_Calendar__c WHERE User_Infusion_Date_Id__r.Id=:infusion_DateList[0].Id];
                }
                if(lstUserCalendar.size() > 0){
                    for (User_Calendar__c ucal : lstUserCalendar) {
                        List< Notification__c > lstNotification = new List<Notification__c>();
                        if (Schema.sObjectType.Notification__c.isAccessible())
                        lstNotification =  [select id from Notification__c where RecordId__c=:ucal.Id];
                        ucal.Event_Type__c=ucal.Event_Type__c+'-U';
                        if(lstNotification.size() > 0){
                            for (Notification__c nf : lstNotification) {
                                lstNotifications.add(nf); 
                            }                           
                        }
                    
                    }                   
                    if(Schema.sObjectType.User_Calendar__c.isUpdateable()){
                    		update lstUserCalendar;
                    }
                    if(lstNotifications.size() > 0){
                        if(Schema.sObjectType.Notification__c.isDeletable()){
                    		delete lstNotifications;
                    	} 
                    }   
                }                
            } // update end here
        
            List<User_Calendar__c> userCalendarList=new List<User_Calendar__c>();
            List<User_Calendar__c> userLabTrackerList=new List<User_Calendar__c>();
        
             
            Date infusion_Date = infusion_DateList[0].Infusion_Date__c;
            
           
            List<Audit_Log__c> lstAudit = new List<Audit_Log__c>();
            Audit_Log__c objAudit_Log = MasterConfigController.createAuditRecord(infusion_DateList[0].Id,JSON.serialize(trigger.new),'User_Infusion_Dates__c','Insert');
            lstAudit.add(objAudit_Log);
            if( (!lstAudit.isEmpty() && lstAudit.size() > 0) && (Schema.sObjectType.Audit_Log__c.isCreateable()) ) {
             insert lstAudit;
           }
        
         if(Schema.sObjectType.Master_Configuration__c.isAccessible()){
           List<Master_Configuration__c> mcList =[SELECT Calendar_Activity__c,Calendar_Activity_desc__c,Calendar_Activity_duration__c,Calendar_Activity_duration_Type__c,Calendar_email_template__c,First_Notification__c,Second_Notification__c 
                                                FROM Master_Configuration__c where RecordType.Name='Calendar Activities'];
            for (Master_Configuration__c calAct : mcList) {    
            if(calAct.Calendar_Activity_duration__c!=null ){
                String durationType=calAct.Calendar_Activity_duration_Type__c;
                Integer duration=integer.valueof(calAct.Calendar_Activity_duration__c);
                String day='';
                String Week='';
                String FirstNotification=''; 
                String SecondNotification='';
                Integer numberDaysDue;
                Date Dateone;
                if(durationType.equalsignorecase('Month')){
                    Dateone = infusion_Date.addMonths(duration);
                    numberDaysDue = infusion_Date.daysBetween(Dateone);
                }else if(durationType.equalsignorecase('Year')){
                    Dateone = infusion_Date.addYears(duration);
                    numberDaysDue = infusion_Date.daysBetween(Dateone);
                }else if(durationType.equalsignorecase('Week')){
                    duration=duration*7;
                    Dateone = infusion_Date.addDays(duration);
                    numberDaysDue = infusion_Date.daysBetween(Dateone);
                }else{
                    Dateone = infusion_Date.addDays(duration);
                    numberDaysDue = infusion_Date.daysBetween(Dateone);
                }
                if(calAct.First_Notification__c !=null && calAct.First_Notification__c !=''){
                    Integer nDuration=integer.valueof(calAct.First_Notification__c);
                    Date nDate=infusion_Date.addDays(nDuration);
                    FirstNotification = string.valueofGmt(nDate);
                }
                if(calAct.Second_Notification__c !=null && calAct.Second_Notification__c !=''){
                    Integer nDuration=integer.valueof(calAct.Second_Notification__c);
                    Date nDate=infusion_Date.addDays(nDuration);
                    SecondNotification = string.valueofGmt(nDate);            
                }
                day=string.valueof(numberDaysDue);
                week=string.valueof(numberDaysDue/7);
                string Datestr = string.valueofGmt(Dateone);
                if(Schema.sObjectType.User_Calendar__c.isCreateable()){
                User_Calendar__c userCalendar=new User_Calendar__c();
                User_Calendar__c labtracker=new User_Calendar__c();
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Activity__c.isCreateable())
                userCalendar.Calendar_Activity__c=calAct.Calendar_Activity_desc__c;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_email_template__c.isCreateable())
                userCalendar.Calendar_email_template__c=calAct.Calendar_email_template__c;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Activity_Date__c.isCreateable())
                userCalendar.Calendar_Activity_Date__c=Datestr;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Week__c.isCreateable())
                userCalendar.Calendar_Week__c=week;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Day__c.isCreateable())
                userCalendar.Calendar_Day__c=day;
                if(Schema.sObjectType.User_Calendar__c.fields.Second_Notification_Date__c.isCreateable())
                userCalendar.Second_Notification_Date__c=SecondNotification;
                if(Schema.sObjectType.User_Calendar__c.fields.First_Notification_Date__c.isCreateable())
                userCalendar.First_Notification_Date__c=FirstNotification;
                if(Schema.sObjectType.User_Calendar__c.fields.User_Infusion_Date_Id__c.isCreateable())
                userCalendar.User_Infusion_Date_Id__c=infusion_DateList[0].id;
                if(Schema.sObjectType.User_Calendar__c.fields.Event_Type__c.isCreateable())
                userCalendar.Event_Type__c='CALENDAR';
                userCalendarList.add(userCalendar);
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Activity__c.isCreateable())
                labtracker.Calendar_Activity__c=calAct.Calendar_Activity_desc__c;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Activity_Date__c.isCreateable())
                labtracker.Calendar_Activity_Date__c=Datestr;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Week__c.isCreateable())
                labtracker.Calendar_Week__c=week;
                if(Schema.sObjectType.User_Calendar__c.fields.Calendar_Day__c.isCreateable())
                labtracker.Calendar_Day__c=day;
                if(Schema.sObjectType.User_Calendar__c.fields.User_Infusion_Date_Id__c.isCreateable())
                labtracker.User_Infusion_Date_Id__c=infusion_DateList[0].id;
                if(Schema.sObjectType.User_Calendar__c.fields.Event_Type__c.isCreateable())
                labtracker.Event_Type__c='LABTRACKER';
                userLabTrackerList.add(labtracker);

                }
                
            }
        
        }
         }
            if(userCalendarList.size() > 0){
                if (Schema.sObjectType.User_Calendar__c.isCreateable()){
                 insert userCalendarList;
                }
                 insert userLabTrackerList[0];
            }
            // Insert end here
    }

}