force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit_Log</label>
    <nameField>
        <displayFormat>AUD-{0000000}</displayFormat>
        <label>Audit_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit_Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template of object to which we need to send email</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NT-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store email address to whom email will be send</description>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <description>Field to store email template name</description>
    <label>Email Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Field to store Id of record to which email should go</description>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Trigger_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Trigger_DateTime__c</fullName>
    <description>Field to store the triggering date time of email</description>
    <label>Trigger DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/User_Calendar__c.object-meta.xml
<CustomObject>
    <label>User Calendar</label>
    <nameField>
        <label>User Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Calendar_email_template</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event_Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/First_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Date__c</fullName>
    <label>First_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Second_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Date__c</fullName>
    <label>Second_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/userCalendarTriggerHelper.cls
public with sharing class userCalendarTriggerHelper {
    /**********************************************************************************************
@Description: Trigger that fires when record inserts to User_Calendar__c
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public static void afterInsertHelper( list<User_Calendar__c>  userCalendarList) {
     List<Audit_Log__c> lstAudit = new List<Audit_Log__c>();
     //list<User_Calendar__c>  userCalendarList=trigger.new;
     List<Notification__c> notificationList=new List<Notification__c>();
    User activeUser = new User();
        for (User_Calendar__c usercal : userCalendarList) {
             Audit_Log__c objAudit_Log = MasterConfigController.createAuditRecord(usercal.Id,JSON.serialize(usercal),'User_Calendar__c','Insert');
             lstAudit.add(objAudit_Log);
             if(usercal != null && usercal.Event_Type__c != null && usercal.Event_Type__c.equals('CALENDAR') && usercal.Calendar_email_template__c !=null && usercal.Calendar_email_template__c!=''){
                     String userName = UserInfo.getUserName();
                 if (Schema.sObjectType.User.isAccessible()){
                      activeUser = [Select Email From User where Username = : userName limit 1];
                 }
                     String userEmail = activeUser.Email;
                     String scheduleDate=usercal.First_Notification_Date__c;
                     Date scheduleDt=Date.valueOf(scheduleDate);
                     Notification__c notification=new Notification__c();
                     if(Schema.sObjectType.Notification__c.fields.Email__c.isCreateable())
                     notification.Email__c=userEmail;
                     if(Schema.sObjectType.Notification__c.fields.Email_Type__c.isCreateable())
                     notification.Email_Type__c=usercal.Calendar_email_template__c;
                     if(Schema.sObjectType.Notification__c.fields.RecordId__c.isCreateable())
                     notification.RecordId__c=usercal.id;
                     if(Schema.sObjectType.Notification__c.fields.Trigger_DateTime__c.isCreateable())
                     notification.Trigger_DateTime__c=scheduleDt;
                     notificationList.add(notification);
                 if(usercal.Second_Notification_Date__c !=null && usercal.Second_Notification_Date__c!=''){
                     scheduleDate=usercal.Second_Notification_Date__c;
                     scheduleDt=Date.valueOf(scheduleDate);
                     Notification__c notification2=new Notification__c();
                     if(Schema.sObjectType.Notification__c.fields.Email__c.isCreateable())
                     notification2.Email__c=userEmail;
                     if(Schema.sObjectType.Notification__c.fields.Email_Type__c.isCreateable())
                     notification2.Email_Type__c=usercal.Calendar_email_template__c;
                     if(Schema.sObjectType.Notification__c.fields.RecordId__c.isCreateable())
                     notification2.RecordId__c=usercal.id;
                     if(Schema.sObjectType.Notification__c.fields.Trigger_DateTime__c.isCreateable())
                     notification2.Trigger_DateTime__c=scheduleDt;
                     notificationList.add(notification2);
                 }
           	}
          }
          if(notificationList.size() > 0 && Schema.sObjectType.Notification__c.isCreateable()){
                 insert notificationList;
          }
          if( !lstAudit.isEmpty() && lstAudit.size() > 0 && Schema.sObjectType.Audit_Log__c.isCreateable() ) {
              
                insert lstAudit;
              
          }
}

}