force-app/main/default/objects/Merge_Field_Mapping__mdt/Merge_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Merge Field Mapping</label>
    <pluralLabel>Merge Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Merge_Field_Mapping__mdt/fields/Merge_Field__c.field-meta.xml
<CustomField>
    <fullName>Merge_Field__c</fullName>
    <label>Merge Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merge_Field_Mapping__mdt/fields/Priority_Order__c.field-meta.xml
<CustomField>
    <fullName>Priority_Order__c</fullName>
    <label>Priority Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Merge_Field_Mapping__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Notification</fullName>
                <default>true</default>
                <label>Notification</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template of object to which we need to send email</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NT-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store email address to whom email will be send</description>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <description>Field to store email template name</description>
    <label>Email Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <description>field to store status of email notification</description>
    <label>Notification Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Field to store Id of record to which email should go</description>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Trigger_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Trigger_DateTime__c</fullName>
    <description>Field to store the triggering date time of email</description>
    <label>Trigger DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/User_Calendar__c.object-meta.xml
<CustomObject>
    <label>User Calendar</label>
    <nameField>
        <label>User Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Calendar__c/fields/User_Infusion_Date_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Infusion_Date_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Infusion Dates</label>
    <referenceTo>User_Infusion_Dates__c</referenceTo>
    <relationshipLabel>User Calendar</relationshipLabel>
    <relationshipName>User_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/User_Infusion_Dates__c.object-meta.xml
<CustomObject>
    <label>User Infusion Dates</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Infusion_Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MergeFieldReplacerTest.cls
/**********************************************************************************************
@Description: Test class for MergeFieldReplacer coverage on method replaceMergeFields 
 
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
@isTest
public class MergeFieldReplacerTest {
    @testSetup
    static void setUpData(){
        User_Infusion_Dates__c objUserInfusionDates = TestDataFactory.createUser_InfusionDate(true);
        User_Calendar__c objUCal = TestDataFactory.createUser_Calendar(false);
        objUCal.User_Infusion_Date_Id__c = objUserInfusionDates.Id;
        insert objUCal;
        Notification__c objNotification = new Notification__c();
        objNotification.Email__c='TestEmail@testacc.xyz';
        objNotification.Email_Type__c='Experience Cloud: New Member Welcome Email';
        objNotification.RecordId__c=objUCal.Id;
        objNotification.Trigger_DateTime__c=system.now();
        objNotification.Notification_Status__c='';
        insert objNotification;
    }
    @IsTest
    static void testReplaceMergeFields(){
        Test.startTest();
        EmailMessageService objEmailMessageService = new EmailMessageService();
        Notification__c notify=[Select id,Email_Type__c,Email__c,RecordId__c,Trigger_DateTime__c,Notification_Status__c from Notification__c where Email__c='TestEmail@testacc.xyz' limit 1];
        List<Notification__c> lstNotificationToUpdate =objEmailMessageService.sendSinglemail(notify);
        //MergeFieldReplacer.replaceMergeFields( e.Subject,'Notification', objNotification.RecordId__c, new<String> {'UserName'} );
        Test.stopTest();
        System.assertNotEquals(lstNotificationToUpdate.size(), 0,'List is not empty');
    }
    @IsTest
    static void testReplaceMergeFields1(){
        List<EmailTemplate> lstEmailTemp = [SELECT 
                                            Id
                                            , Name  
                                            , Subject  
                                            , Body
                                            , HtmlValue
                                            , TemplateType
                                        FROM 
                                            EmailTemplate 
                                        WHERE 
                                            Folder.Name = 'Notification'
                               AND Name = 'Experience Cloud: New Member Welcome Email'
                                        ];
        Set<String> setApiNames = new Set<String>();
        List<Merge_Field_Mapping__mdt> listMergeFldMdt = new List<Merge_Field_Mapping__mdt>();
        //get configured merge field mappings
        for( Merge_Field_Mapping__mdt mdt : [ SELECT
                                             Field_API_Name__c
                                             , Merge_Field__c
                                             , Process_Name__c
                                             , Priority_Order__c
                                             FROM
                                             Merge_Field_Mapping__mdt
                                             WHERE
                                             Process_Name__c = 'Notification'
                                             ORDER BY 
                                             Priority_Order__c ASC ] ) {
				setApiNames.add( mdt.Field_API_Name__c );
                listMergeFldMdt.add( mdt );
		}      
        Notification__c notify=[Select id,Email_Type__c,Email__c,RecordId__c,Trigger_DateTime__c,Notification_Status__c from Notification__c where Email__c='TestEmail@testacc.xyz' limit 1];
        Test.startTest();        
        	String replacer=MergeFieldReplacer.replaceMergeFields(lstEmailTemp[0].Body,'Notification'
                                                                 , Id.valueOf( notify.RecordId__c)
                                                  				, setApiNames , listMergeFldMdt);
        //MergeFieldReplacer.replaceMergeFields( e.Subject,'Notification', objNotification.RecordId__c, new<String> {'UserName'} );
        Test.stopTest();
        System.assertNotEquals('3', replacer,'Replacer is not empty');
    }
}