force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Actividad del calendario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_desc__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_desc__c</fullName>
    <label>Calendario Actividad Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_duration__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_duration__c</fullName>
    <label>Duración de la actividad del calendario</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_Duration_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Duration_Type__c</fullName>
    <label>Calendario Actividad Duración Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Plantilla de correo electrónico de calen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infusion day</fullName>
            </value>
            <value>
                <fullName>New case generated</fullName>
            </value>
            <value>
                <fullName>Pre infusion</fullName>
            </value>
            <value>
                <fullName>Post Infusion week1</fullName>
            </value>
            <value>
                <fullName>Post Infusion week2</fullName>
            </value>
            <value>
                <fullName>Post Infusion week3</fullName>
            </value>
            <value>
                <fullName>Post Infusion week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>País</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/End_Weight__c.field-meta.xml
<CustomField>
    <fullName>End_Weight__c</fullName>
    <label>End Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/First_Notification__c.field-meta.xml
<CustomField>
    <fullName>First_Notification__c</fullName>
    <label>Primera Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Address__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Address__c</fullName>
    <label>Dirección del centro de infusión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Id__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Id__c</fullName>
    <label>Infusion Center Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Name__c</fullName>
    <label>Nombre del centro de infusión</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Nombre de la Institución</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Enlace</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Código postal</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Second_Notification__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification__c</fullName>
    <label>Segunda Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity__c</fullName>
    <label>Actividad Calendario Español</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity_Description__c</fullName>
    <label>Descripción de la actividad del calendar</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Start_Weight__c.field-meta.xml
<CustomField>
    <fullName>Start_Weight__c</fullName>
    <label>Start Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Expresar</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Nombre de entrenamiento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Kaltura Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial5_5__c.field-meta.xml
<CustomField>
    <fullName>Vial5_5__c</fullName>
    <label>Vial de 5,5 mLa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial8_3__c.field-meta.xml
<CustomField>
    <fullName>Vial8_3__c</fullName>
    <label>Vial de 8,3 mLb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Viales_Totales__c.field-meta.xml
<CustomField>
    <fullName>Viales_Totales__c</fullName>
    <label>Viales Totales por Kit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Weight_Range__c.field-meta.xml
<CustomField>
    <fullName>Weight_Range__c</fullName>
    <label>Peso del Paciente (kg)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/classes/MasterConfigControllerTest.cls
/**********************************************************************************************
@Description: An apex page controller that exposes the ZOE Master Configurations
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
@isTest
public class MasterConfigControllerTest {
    @testSetup static void setup() {
        test.startTest();
        Id zkitrecordtypeid=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Z-Kit Calculator').getRecordTypeId();
        Id trainingtypeid=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
        Id instrecordtypeid=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Institution Master').getRecordTypeId();
        Id calendarrecordtypeid=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Calendar Activities').getRecordTypeId();
        List<Master_Configuration__c> configlist=new List<Master_Configuration__c>();
        Master_Configuration__c conf=new Master_Configuration__c();
        conf.Infusion_Center_Id__c='Test';
        conf.Infusion_Center_Name__c='Test';
        conf.Infusion_Center_Address__c='Test';
        conf.Street__c='Test';
        conf.State__c='Test';
        conf.City__c='Test';
        conf.Country__c='Test';
        conf.PostalCode__c='123456';
        conf.Active__c= true;
        conf.Address_2__c='test';
         conf.Address_1__c='test';   
         conf.Address_3__c='test';
        conf.Calendar_Activity__c='test';
        conf.Calendar_Activity_desc__c='test';
        conf.Calendar_Activity_duration__c='12';
        conf.Calendar_Activity_Duration_Type__c='Day';
        conf.Calendar_email_template__c='Infusion day';
        conf.Description__c='test';
        conf.Dosage__c= 2;
        conf.End_Weight__c= 2;
        conf.First_Notification__c='test';
        conf.Institution_Id__c='test';
        conf.Institution_Name__c='test';
        conf.Link__c='www.salesforce.com';
        conf.Weight_Range__c='1-2';
        conf.Record_Status__c='t';
        conf.Second_Notification__c='test';
        conf.Spanish_Calendar_Activity__c='test';
        conf.Spanish_Calendar_Activity_Description__c='test';
        conf.Start_Weight__c= 2;
        conf.Training_Name__c='test';
        conf.Type__c='PDF';
        conf.Vial5_5__c= 1;
        conf.Vial8_3__c= 1;
        conf.Viales_Totales__c= 1;
         conf.RecordTypeId=zkitrecordtypeid;
        configlist.add(conf);
        Master_Configuration__c conf1=new Master_Configuration__c();
        
        
          conf1.Infusion_Center_Id__c='Test';
        conf1.Infusion_Center_Name__c='Test';
        conf1.Infusion_Center_Address__c='Test';
        conf1.Street__c='Test';
        conf1.State__c='Test';
        conf1.City__c='Test';
        conf1.Country__c='Test';
        conf1.PostalCode__c='123456';
        conf1.Active__c= true;
        conf1.Address_2__c='test';
         conf1.Address_1__c='test';   
         conf1.Address_3__c='test';
        conf1.Calendar_Activity__c='test';
        conf1.Calendar_Activity_desc__c='test';
        conf1.Calendar_Activity_duration__c='12';
        conf1.Calendar_Activity_Duration_Type__c='Day';
        conf1.Calendar_email_template__c='Infusion day';
        conf1.Description__c='test';
        conf1.Dosage__c= 2;
        conf1.End_Weight__c= 2;
        conf1.First_Notification__c='test';
        conf1.Institution_Id__c='test';
        conf1.Institution_Name__c='test';
        conf1.Link__c='https://www.youtube.com/embed/VSsGwM7xuCw';
        conf1.Weight_Range__c='1-2';
        conf1.Record_Status__c='t';
        conf1.Second_Notification__c='test';
        conf1.Spanish_Calendar_Activity__c='test';
        conf1.Spanish_Calendar_Activity_Description__c='test';
        conf1.Start_Weight__c= 2;
        conf1.Training_Name__c='test';
        conf1.Type__c='Video';
        conf1.Vial5_5__c= 1;
        conf1.Vial8_3__c= 1;
        conf1.Viales_Totales__c= 1;
       conf1.RecordTypeId=trainingtypeid;
        configlist.add(conf1);
        Master_Configuration__c conf2=new Master_Configuration__c();
         conf2.Infusion_Center_Id__c='Test';
        conf2.Infusion_Center_Name__c='Test';
        conf2.Infusion_Center_Address__c='Test';
        conf2.Street__c='Test';
        conf2.State__c='Test';
        conf2.City__c='Test';
        conf2.Country__c='Test';
        conf2.PostalCode__c='123456';
        conf2.Active__c= true;
        conf2.Address_2__c='test';
         conf2.Address_1__c='test';   
         conf2.Address_3__c='test';
        conf2.Calendar_Activity__c='test';
        conf2.Calendar_Activity_desc__c='test';
        conf2.Calendar_Activity_duration__c='12';
        conf2.Calendar_Activity_Duration_Type__c='Day';
        conf2.Calendar_email_template__c='Infusion day';
        conf2.Description__c='test';
        conf2.Dosage__c= 2;
        conf2.End_Weight__c= 2;
        conf2.First_Notification__c='test';
        conf2.Institution_Id__c='test';
        conf2.Institution_Name__c='test';
        conf2.Link__c='www.salesforce.com';
        conf2.Weight_Range__c='1-2';
        conf2.Record_Status__c='t';
        conf2.Second_Notification__c='test';
        conf2.Spanish_Calendar_Activity__c='test';
        conf2.Spanish_Calendar_Activity_Description__c='test';
        conf2.Start_Weight__c= 2;
        conf2.Training_Name__c='test';
        conf2.Type__c='PDF';
        conf.Vial5_5__c= 1;
        conf2.Vial8_3__c= 1;
        conf2.Viales_Totales__c= 1;
        conf2.RecordTypeId=instrecordtypeid;
        configlist.add(conf2);
        
        Master_Configuration__c conf3=new Master_Configuration__c();
        conf3.Infusion_Center_Id__c='Test';
        conf3.Infusion_Center_Name__c='Test';
        conf3.Infusion_Center_Address__c='Test';
        conf3.Street__c='Test';
        conf3.State__c='Test';
        conf3.City__c='Test';
        conf3.Country__c='Test';
        conf3.PostalCode__c='123456';
        conf3.Active__c= true;
        conf3.Address_2__c='test';
        conf3.Address_1__c='test';   
        conf3.Address_3__c='test';
        conf3.Calendar_Activity__c='test';
        conf3.Calendar_Activity_desc__c='test';
        conf3.Calendar_Activity_duration__c='12';
        conf3.Calendar_Activity_Duration_Type__c='Day';
        conf3.Calendar_email_template__c='Infusion day';
        conf3.Description__c='test';
        conf3.Dosage__c= 2;
        conf3.End_Weight__c= 2;
        conf3.First_Notification__c='test';
        conf3.Institution_Id__c='test';
        conf3.Institution_Name__c='test';
        conf3.Link__c='www.salesforce.com';
        conf3.Weight_Range__c='1-2';
        conf3.Record_Status__c='t';
        conf3.Second_Notification__c='test';
        conf3.Spanish_Calendar_Activity__c='test';
        conf3.Spanish_Calendar_Activity_Description__c='test';
        conf3.Start_Weight__c= 2;
        conf3.Training_Name__c='test';
        conf3.Type__c='PDF';
        conf3.Vial5_5__c= 1;
        conf3.Vial8_3__c= 1;
        conf3.Viales_Totales__c= 1;
        conf3.RecordTypeId=calendarrecordtypeid;
        configlist.add(conf3);
        
        insert configlist;
        test.stopTest();
       }
    static testMethod void configTest() {
        Map<String,String> dosages=new Map<String,String>();
        dosages=MasterConfigController.getDosage();
        System.assertNotEquals(dosages.size(),0,'Dosage size is greater than zero');
        Map<String,String> dosage=InfusionCenter.getDosage();
        System.assertNotEquals(null, dosage,'Dosage is not null'); 
        List<Master_Configuration__c> trainings=MasterConfigController.gettrainings();
        System.assertNotEquals(trainings.size(),0,'Trainings size is greater than zero');
        List<Master_Configuration__c> institutionCenters=MasterConfigController.getInstitutionName();
        System.assertNotEquals(institutionCenters.size(),0,'InstitutionCenters size is greater than zero');
        List<String> instituteNames=ZOE_LoginCntrl.getInstitutionName();
        System.assertNotEquals(instituteNames.size(),0,'InstitutionNames size is greater than zero');
    }
    static testMethod void getSelectedOptions() {
          String value1='puede o no tener una relación causal con el medicamento recibido';
         String value2='Dentro de las 24hs de haber tomado contacto con el mismo';
         String value3='Si, porque existe un escenario especial';
         String value4='Casilla genérica de mail, página web';
        
        Integer count = MasterConfigController.getSelectedOptions(value1,value2,value3,value4);
        System.assertNotEquals(count,0,'Count is greater than zero');
    }
     static testMethod void getSelectedOptions2() {
          String value1='– 60 °C';
         String value2='12 horas';
         String value3='Verdadero';
         String value4='Falso';
         String value5='El vial no se debe usar';
         String value6='Verdadero';
         String value7='8 horas';
        Integer count = MasterConfigController.getSelectedOptions2(value1,value2,value3,value4,value5,value6,value7);
        System.assertNotEquals(count,0,'Count is greater than zero');
     }
     static testMethod void getSelectedOptions3() {
          String value1='Todas las anteriores';
         String value2='Corticoides sistémicos (prednisolona oral 1mg/kg/día)';
         String value3='Verdadero';
         String value4='Infusión lenta, durante 60 minutos';
         String value5='Colocar un catéter primario en una vena periférica; y un catéter de respaldo';
         String value6='3 meses';
        Integer count = MasterConfigController.getSelectedOptions3(value1,value2,value3,value4,value5,value6);
        System.assertNotEquals(count,0,'Count is greater than zero');
     }
    }