force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Actividad del calendario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_desc__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_desc__c</fullName>
    <label>Calendario Actividad Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_duration__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_duration__c</fullName>
    <label>Duración de la actividad del calendario</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_Duration_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Duration_Type__c</fullName>
    <label>Calendario Actividad Duración Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Plantilla de correo electrónico de calen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infusion day</fullName>
            </value>
            <value>
                <fullName>New case generated</fullName>
            </value>
            <value>
                <fullName>Pre infusion</fullName>
            </value>
            <value>
                <fullName>Post Infusion week1</fullName>
            </value>
            <value>
                <fullName>Post Infusion week2</fullName>
            </value>
            <value>
                <fullName>Post Infusion week3</fullName>
            </value>
            <value>
                <fullName>Post Infusion week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>País</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/End_Weight__c.field-meta.xml
<CustomField>
    <fullName>End_Weight__c</fullName>
    <label>End Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/First_Notification__c.field-meta.xml
<CustomField>
    <fullName>First_Notification__c</fullName>
    <label>Primera Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Address__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Address__c</fullName>
    <label>Dirección del centro de infusión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Id__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Id__c</fullName>
    <label>Infusion Center Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Name__c</fullName>
    <label>Nombre del centro de infusión</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Nombre de la Institución</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Enlace</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Código postal</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Second_Notification__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification__c</fullName>
    <label>Segunda Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity__c</fullName>
    <label>Actividad Calendario Español</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity_Description__c</fullName>
    <label>Descripción de la actividad del calendar</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Start_Weight__c.field-meta.xml
<CustomField>
    <fullName>Start_Weight__c</fullName>
    <label>Start Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Expresar</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Nombre de entrenamiento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Kaltura Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial5_5__c.field-meta.xml
<CustomField>
    <fullName>Vial5_5__c</fullName>
    <label>Vial de 5,5 mLa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial8_3__c.field-meta.xml
<CustomField>
    <fullName>Vial8_3__c</fullName>
    <label>Vial de 8,3 mLb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Viales_Totales__c.field-meta.xml
<CustomField>
    <fullName>Viales_Totales__c</fullName>
    <label>Viales Totales por Kit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Weight_Range__c.field-meta.xml
<CustomField>
    <fullName>Weight_Range__c</fullName>
    <label>Peso del Paciente (kg)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/User_Calendar__c.object-meta.xml
<CustomObject>
    <label>User Calendar</label>
    <nameField>
        <label>User Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Calendar Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Calendar_email_template</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event_Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/First_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Date__c</fullName>
    <label>First_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Second_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Date__c</fullName>
    <label>Second_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/User_Infusion_Date_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Infusion_Date_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Infusion Dates</label>
    <referenceTo>User_Infusion_Dates__c</referenceTo>
    <relationshipLabel>User Calendar</relationshipLabel>
    <relationshipName>User_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/User_Infusion_Dates__c.object-meta.xml
<CustomObject>
    <label>User Infusion Dates</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Infusion_Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Infusion_Dates__c/fields/Infusion_Date__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Date__c</fullName>
    <label>Infusion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UserCalendarControllerTest.cls
/**********************************************************************************************
@Description: An apex page controller that exposes the UserCalendarController Functionalities
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
@isTest
public class UserCalendarControllerTest {
    @testSetup
    static void setUpData(){
        Profile objProfile = [SELECT Id FROM Profile WHERE Name='Customer Community Plus User']; 
                
        User runAsUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        String contactid;
        System.runAs ( runAsUser ) {          
            Account testAccount = new Account();
            testAccount.Name='Test Account' ;
            insert testAccount;
            
            Contact cont = new Contact();
            cont.FirstName='Test';
            cont.LastName='Test';
            cont.Accountid= testAccount.id;
            insert cont;
            contactid = cont.Id;
            
            User_Calendar__c objUserCalendar = TestDataFactory.createUser_Calendar(false);
            objUserCalendar.Event_Type__c ='CALENDAR';
            objUserCalendar.Calendar_email_template__c = 'Pre infusion';
            objUserCalendar.First_Notification_Date__c = '2022-03-16 00:00:00';
            objUserCalendar.Second_Notification_Date__c = '2022-03-19 00:00:00';
            insert objUserCalendar ;
            
            User_Calendar__c objUserCalendar1 = TestDataFactory.createUser_Calendar(false);
            objUserCalendar1.Event_Type__c ='CALENDAR';
            insert objUserCalendar1 ;
            
            User_Infusion_Dates__c objUserInfusionDates  = new User_Infusion_Dates__c ();
            objUserInfusionDates.Name = 'Test user user infusion';
            //objUserInfusionDates.OwnerId=objuser.Id;
            objUserInfusionDates.Status__c='Active';
            objUserInfusionDates.Infusion_Date__c = system.today()+3;
            insert objUserInfusionDates;
            
        }        
        User objUser = new User(Alias = 'standt', Email='divyanidadavolu231@gmail.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = objProfile.Id, 	ContactId = contactid, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='standardusertest@novartis.com');
        
        insert objUser;
        
        
    }
     static testmethod void getUserCalendarEventsTest() {
        //@Description: Setup test data
        //@Description: This code runs as the system user
        User user= [Select id from User where LastName='Testing' Limit 1];
        System.runAs(user) {
            
            
            Test.StartTest();
            List<User_Calendar__c> lstUserCalendar =  UserCalendarController.getUserCalendarEvents(user.Id);
            system.assertNotEquals(1, lstUserCalendar.size(),'User calendar list is not equals to one');
            //system.assertEquals('Test user calender name', lstUserCalendar[0].Name);
            UserCalendarController.dateConversion('08-03-2018');
            Test.StopTest();
        }
    }
    
    static testmethod void getUserCalendarEventsNegativeTest() {
        //@Description: Setup test data
        User user= [Select id from User where UserName='standardusertest@novartis.com' Limit 1];
        
        System.runAs(user) {
            
            Test.StartTest();
            List<User_Calendar__c> lstUser_Calendar =  UserCalendarController.getUserCalendarEvents(user.Id);
            system.assertEquals(0, lstUser_Calendar.size(),'Calendar size is zero');
            Test.StopTest();
        }
    }
    
    static testmethod void getCalMapTest() {
        //@Description: Setup test data
        //@Description: This code runs as the system user
        User user= [Select id from User where LastName='Testing' Limit 1];
        System.runAs(user) {
            Id calendaractivity=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Calendar Activities').getRecordTypeId();
            Master_Configuration__c conf=new Master_Configuration__c();
            conf.Calendar_Activity__c='Test';
            conf.Calendar_Activity_desc__c='Test';
            conf.Calendar_Activity_duration_Type__c='Month';
            conf.Calendar_Activity_duration__c='1';
            conf.RecordTypeId=calendaractivity;
            
            conf.Infusion_Center_Id__c='Test';
            conf.Infusion_Center_Name__c='Test';
            conf.Infusion_Center_Address__c='Test';
            conf.Street__c='Test';
            conf.State__c='Test';
            conf.City__c='Test';
            conf.Country__c='Test';
            conf.PostalCode__c='123456';
            conf.Active__c= true;
            conf.Address_2__c='test';
            conf.Address_1__c='test';   
            conf.Address_3__c='test';
            conf.Calendar_Activity__c='Test';
            conf.Calendar_Activity_desc__c='Test';
            conf.Calendar_Activity_duration__c='1';
            conf.Calendar_Activity_Duration_Type__c='Day';
            conf.Calendar_email_template__c='Infusion day';
            conf.Description__c='test';
            conf.Dosage__c= 2;
            conf.End_Weight__c= 2;
            conf.First_Notification__c='1';
            conf.Institution_Id__c='test';
            conf.Institution_Name__c='test';
            conf.Link__c='www.salesforce.com';
            conf.Weight_Range__c='1-2';
            conf.Record_Status__c='t';
            conf.Second_Notification__c='2';
            conf.Spanish_Calendar_Activity__c='test';
            conf.Spanish_Calendar_Activity_Description__c='test';
            conf.Start_Weight__c= 2;
            conf.Training_Name__c='test';
            conf.Type__c='PDF';
            conf.Vial5_5__c= 1;
            conf.Vial8_3__c= 1;
            conf.Viales_Totales__c= 1;
            conf.RecordTypeId=calendaractivity;
            insert conf;
            User_Infusion_Dates__c objUserInfusionDates  = new User_Infusion_Dates__c ();
            objUserInfusionDates.Name = 'Test user user infusion';
            objUserInfusionDates.OwnerId=user.Id;
            objUserInfusionDates.Status__c='Active';
            objUserInfusionDates.Infusion_Date__c = system.today()+3;
            insert objUserInfusionDates;
            
            User_Infusion_Dates__c objuserinfusion= [Select id from User_Infusion_Dates__c where Name='Test user user infusion' Limit 1]; 
            
            Test.StartTest();
            Map<String, String> mapidName = UserCalendarController.getCalMap(user.Id);
            system.assertEquals(1, mapidName.size(),'Calendar map is eqauls to zero');
            Test.StopTest();
        }
    }
    
    static testmethod void getAllUsersCalenderRecTest() {
        //@Description: Setup test data
        //@Description: This code runs as the system user
        User user= [Select id from User where UserName='standardusertest@novartis.com' Limit 1];
        System.runAs(user) {
            User_Infusion_Dates__c objUser_Infusion_Dates = TestDataFactory.createUser_InfusionDate(true);
            
            User_Calendar__c objUser_Calendar = TestDataFactory.createUser_Calendar(false);
            objUser_Calendar.Event_Type__c ='LABTRACKER';
            objUser_Calendar.User_Infusion_Date_Id__c = objUser_Infusion_Dates.Id;
            insert objUser_Calendar ;
            
            Test.StartTest();
            List<UserCalendarController.UserCalWrapper> lstUserCalWrap = UserCalendarController.getAllUsersCalenderRec(user.Id);
            system.assertEquals(1, lstUserCalWrap.size(),'User calendar list is equals to zero');
            system.assertEquals('1', lstUserCalWrap[0].calday,'User calendar call day is equals to one');
            Test.StopTest();
        }
    }
    
    static testmethod void getEncryptUserCalRec() {
        
    }
    
    static testmethod void getAllUsersCalenderRecByPatientId() {
        //@Description: Setup test data
        //@Description: This code runs as the system user
        User user= [Select id from User where UserName='standardusertest@novartis.com' Limit 1];
        System.runAs(user) {
            User_Infusion_Dates__c objUserInfusionDates  = new User_Infusion_Dates__c ();
            objUserInfusionDates.Name = 'Test user user infusion';
            objUserInfusionDates.OwnerId=user.Id;
            objUserInfusionDates.Status__c='Active';
            objUserInfusionDates.Infusion_Date__c = system.today()+3;
            insert objUserInfusionDates;
            
            User_Calendar__c objUser_Calendar = TestDataFactory.createUser_Calendar(false);
            objUser_Calendar.Event_Type__c ='LABTRACKER';
            objUser_Calendar.User_Infusion_Date_Id__c = objUserInfusionDates.Id;
            insert objUser_Calendar ;
            
            Test.StartTest();
            List<UserCalendarController.UserCalWrapper> lstUserCalWrap = UserCalendarController.getAllUsersCalenderRec(user.Id);
            system.assertEquals(1, lstUserCalWrap.size(),'User calendar call day is equals to zero');
            system.assertEquals('1', lstUserCalWrap[0].calday,'User calendar call day is equals to one');
            UserCalendarController.getAllUsersCalenderRecByPatientId(user.Id,objUserInfusionDates.Id);
            UserCalendarController.getLabtackerChartDetails(user.Id,objUserInfusionDates.Id);
            UserCalendarController.updateFeatureUsage('Calendar');
            UserCalendarController.getUserCalendarEventsByPatient(user.Id,objUserInfusionDates.Id);
            UserCalendarController.getUserCalendarEventsByPatient(user.Id,'all');
            Test.StopTest();
        }
    }
    static testmethod void getAllUsersCalenderAllRecs() {
        //@Description: Setup test data
        //@Description: This code runs as the system user
        User user= [Select id from User where UserName='standardusertest@novartis.com' Limit 1];
        System.runAs(user) {
            
            User_Infusion_Dates__c objUserInfusionDates  = new User_Infusion_Dates__c ();
            objUserInfusionDates.Name = 'Test user user infusion';
            objUserInfusionDates.OwnerId=user.Id;
            objUserInfusionDates.Status__c='Active';
            objUserInfusionDates.Infusion_Date__c = system.today()+3;
            insert objUserInfusionDates;
            User_Calendar__c objUser_Calendar = TestDataFactory.createUser_Calendar(false);
            objUser_Calendar.Event_Type__c ='LABTRACKER';
            objUser_Calendar.User_Infusion_Date_Id__c = objUserInfusionDates.Id;
            insert objUser_Calendar ;
            
            Test.StartTest();
            List<UserCalendarController.UserCalWrapper> lstUserCalWrap = UserCalendarController.getAllUsersCalenderAllRecs(user.Id);
            system.assertEquals(1, lstUserCalWrap.size(),'User calendar call day is equals to zero');
            system.assertEquals('1', lstUserCalWrap[0].calday,'User calendar call day is equals to one');
            /*  UserCalendarController.getAllUsersCalenderRecByPatientId(user.Id,objUserInfusionDates.Id);
UserCalendarController.getLabtackerChartDetails(user.Id,objUserInfusionDates.Id);
UserCalendarController.updateFeatureUsage('Calendar');
UserCalendarController.getUserCalendarEventsByPatient(user.Id,objUserInfusionDates.Id);
UserCalendarController.getUserCalendarEventsByPatient(user.Id,'all'); */
            Test.StopTest();
        }
    }
    static testmethod void UserCalWrapperTest() {
        List<UserCalendarController.UserCalWrapper> usrList=new List<UserCalendarController.UserCalWrapper>();
        UserCalendarController.UserCalWrapper usr=new UserCalendarController.UserCalWrapper();
        User_Infusion_Dates__c objUser_Infusion_Dates = TestDataFactory.createUser_InfusionDate(true);
        usr.calday='01';
        usr.calInfusionDate=System.today();
        usr.calInfusionId=objUser_Infusion_Dates.id;
        usr.calweek='02';
        usr.chopintended='test';
        
        usr.doesDate1=system.today();
        usr.doesDate1_day='01';
        usr.doesDate1_week='02';
        usr.doesDate2=Date.parse('04/04/2022');
        usr.doesDate2_day='01';
        usr.doesDate2_week='03';
        usr.doesDate3=Date.parse('04/05/2022');
        usr.doesDate3_day='01';
        usr.doesDate3_week='04';
        usr.doesDate4=Date.parse('04/06/2022');
        usr.doesDate4_day='02';
        usr.doesDate4_week='05';
        usr.doseOfInfusion='testdoseinfusion';
        usr.isCHOPTable='testchop';
        usr.isDoseInfusionTable='testdoseinf';
        usr.isPLAQUETASTable='testplaq';
        usr.isTRANSAMINASASTable='testtrans';
        usr.paitentid='testpatientId';
        usr.paitentName='testpatientName';
        usr.platelets='testplatelets';
        //usr.recId='testrecid';
        usr.transaminasas_ALT='testalt';
        usr.transaminasas_ALT_CalVal='testcalval';
        usr.transaminasas_ALT_Ref='testaltref';
        usr.userInfustionDate=Date.parse('04/03/2022');
        usrList.add(usr);
        Test.startTest();
        List<UserCalendarController.UserCalWrapper> lstUserCalWrapper =UserCalendarController.updateDose(usrList);
        Test.stopTest();
        System.assertNotEquals(lstUserCalWrapper.size(), 0,'User calendar updated dose details is not eqauls to zero');
        
    }
}