force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Actividad del calendario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_desc__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_desc__c</fullName>
    <label>Calendario Actividad Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_duration__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_duration__c</fullName>
    <label>Duración de la actividad del calendario</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_Duration_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Duration_Type__c</fullName>
    <label>Calendario Actividad Duración Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Plantilla de correo electrónico de calen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infusion day</fullName>
            </value>
            <value>
                <fullName>New case generated</fullName>
            </value>
            <value>
                <fullName>Pre infusion</fullName>
            </value>
            <value>
                <fullName>Post Infusion week1</fullName>
            </value>
            <value>
                <fullName>Post Infusion week2</fullName>
            </value>
            <value>
                <fullName>Post Infusion week3</fullName>
            </value>
            <value>
                <fullName>Post Infusion week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>País</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/End_Weight__c.field-meta.xml
<CustomField>
    <fullName>End_Weight__c</fullName>
    <label>End Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/First_Notification__c.field-meta.xml
<CustomField>
    <fullName>First_Notification__c</fullName>
    <label>Primera Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Address__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Address__c</fullName>
    <label>Dirección del centro de infusión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Id__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Id__c</fullName>
    <label>Infusion Center Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Name__c</fullName>
    <label>Nombre del centro de infusión</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Nombre de la Institución</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Enlace</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Código postal</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Second_Notification__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification__c</fullName>
    <label>Segunda Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity__c</fullName>
    <label>Actividad Calendario Español</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity_Description__c</fullName>
    <label>Descripción de la actividad del calendar</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Start_Weight__c.field-meta.xml
<CustomField>
    <fullName>Start_Weight__c</fullName>
    <label>Start Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Expresar</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Nombre de entrenamiento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Kaltura Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial5_5__c.field-meta.xml
<CustomField>
    <fullName>Vial5_5__c</fullName>
    <label>Vial de 5,5 mLa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial8_3__c.field-meta.xml
<CustomField>
    <fullName>Vial8_3__c</fullName>
    <label>Vial de 8,3 mLb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Viales_Totales__c.field-meta.xml
<CustomField>
    <fullName>Viales_Totales__c</fullName>
    <label>Viales Totales por Kit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Weight_Range__c.field-meta.xml
<CustomField>
    <fullName>Weight_Range__c</fullName>
    <label>Peso del Paciente (kg)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InfusionCenterTest.cls
/**********************************************************************************************
@Description: Test class for InfusionCenter coverage on method getInfusionCenterDetails
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
@isTest
public class InfusionCenterTest {
    @testSetup
    static void setUpData(){
        Id infusioncenterRecordTypeId=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Infusion Center Master').getRecordTypeId();
        Master_Configuration__c conf=new Master_Configuration__c();
        conf.Infusion_Center_Id__c='Test';
        conf.Infusion_Center_Name__c='Test';
        conf.Infusion_Center_Address__c='Test';
        conf.Street__c='Test';
        conf.State__c='Test';
        conf.City__c='Test';
        conf.Country__c='Test';
        conf.PostalCode__c='123456';
        conf.Active__c= true;
        conf.Address_2__c='test';
         conf.Address_1__c='test';   
         conf.Address_3__c='test';
        conf.Calendar_Activity__c='test';
        conf.Calendar_Activity_desc__c='test';
        conf.Calendar_Activity_duration__c='12';
        conf.Calendar_Activity_Duration_Type__c='Day';
        conf.Calendar_email_template__c='Infusion day';
        conf.Description__c='test';
        conf.Dosage__c= 2;
        conf.End_Weight__c= 2;
        conf.First_Notification__c='test';
        conf.Institution_Id__c='test';
        conf.Institution_Name__c='test';
        conf.Link__c='www.salesforce.com';
        conf.Weight_Range__c='1-2';
        conf.Record_Status__c='t';
        conf.Second_Notification__c='test';
        conf.Spanish_Calendar_Activity__c='test';
        conf.Spanish_Calendar_Activity_Description__c='test';
        conf.Start_Weight__c= 2;
        conf.Training_Name__c='test';
        conf.Type__c='PDF';
        conf.Vial5_5__c= 1;
        conf.Vial8_3__c= 1;
        conf.Viales_Totales__c= 1;
        conf.RecordTypeId=infusioncenterRecordTypeId; 
        insert conf;
    }
    static testMethod void getInfusionCenterDetailsTest() {
        test.startTest();
        List<Object> infusion=InfusionCenter.getInfusionCenterDetails(); 
        System.assertNotEquals(infusion.size(),0,'Infusion size is not empty');
        test.stopTest();
    }
}