force-app/main/default/objects/Master_Configuration__c/Master_Configuration__c.object-meta.xml
<CustomObject>
    <label>Master Configuration</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nombre de la configuración maestra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones maestras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Configuration__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Actividad del calendario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_desc__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_desc__c</fullName>
    <label>Calendario Actividad Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_duration__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_duration__c</fullName>
    <label>Duración de la actividad del calendario</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_Activity_Duration_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity_Duration_Type__c</fullName>
    <label>Calendario Actividad Duración Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Plantilla de correo electrónico de calen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Infusion day</fullName>
            </value>
            <value>
                <fullName>New case generated</fullName>
            </value>
            <value>
                <fullName>Pre infusion</fullName>
            </value>
            <value>
                <fullName>Post Infusion week1</fullName>
            </value>
            <value>
                <fullName>Post Infusion week2</fullName>
            </value>
            <value>
                <fullName>Post Infusion week3</fullName>
            </value>
            <value>
                <fullName>Post Infusion week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ciudad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>País</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/End_Weight__c.field-meta.xml
<CustomField>
    <fullName>End_Weight__c</fullName>
    <label>End Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/First_Notification__c.field-meta.xml
<CustomField>
    <fullName>First_Notification__c</fullName>
    <label>Primera Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Address__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Address__c</fullName>
    <label>Dirección del centro de infusión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Id__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Id__c</fullName>
    <label>Infusion Center Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Infusion_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Center_Name__c</fullName>
    <label>Nombre del centro de infusión</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Nombre de la Institución</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Enlace</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Código postal</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Second_Notification__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification__c</fullName>
    <label>Segunda Notificación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity__c</fullName>
    <label>Actividad Calendario Español</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Spanish_Calendar_Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Calendar_Activity_Description__c</fullName>
    <label>Descripción de la actividad del calendar</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Start_Weight__c.field-meta.xml
<CustomField>
    <fullName>Start_Weight__c</fullName>
    <label>Start Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Expresar</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Nombre de entrenamiento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Kaltura Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial5_5__c.field-meta.xml
<CustomField>
    <fullName>Vial5_5__c</fullName>
    <label>Vial de 5,5 mLa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Vial8_3__c.field-meta.xml
<CustomField>
    <fullName>Vial8_3__c</fullName>
    <label>Vial de 8,3 mLb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Viales_Totales__c.field-meta.xml
<CustomField>
    <fullName>Viales_Totales__c</fullName>
    <label>Viales Totales por Kit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Configuration__c/fields/Weight_Range__c.field-meta.xml
<CustomField>
    <fullName>Weight_Range__c</fullName>
    <label>Peso del Paciente (kg)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/User_Calendar__c.object-meta.xml
<CustomObject>
    <label>User Calendar</label>
    <nameField>
        <label>User Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_Activity__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Activity__c</fullName>
    <label>Calendar Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Calendar_email_template__c.field-meta.xml
<CustomField>
    <fullName>Calendar_email_template__c</fullName>
    <label>Calendar_email_template</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event_Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/First_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Date__c</fullName>
    <label>First_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/Second_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Date__c</fullName>
    <label>Second_Notification_Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Calendar__c/fields/User_Infusion_Date_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Infusion_Date_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Infusion Dates</label>
    <referenceTo>User_Infusion_Dates__c</referenceTo>
    <relationshipLabel>User Calendar</relationshipLabel>
    <relationshipName>User_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/User_Infusion_Dates__c.object-meta.xml
<CustomObject>
    <label>User Infusion Dates</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Infusion_Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Infusion_Dates__c/fields/Infusion_Date__c.field-meta.xml
<CustomField>
    <fullName>Infusion_Date__c</fullName>
    <label>Infusion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Infusion_Dates__c/fields/Patient_Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_Reference_ID__c</fullName>
    <description>Unique ID</description>
    <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Patient Reference ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/NewInfusionDateCntrlTest.cls
/**********************************************************************************************
@Description: Test class for NewInfusionDateCntrl coverage on method saveInfuDate
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
@isTest
public class NewInfusionDateCntrlTest {
    @testSetup
    static void setUpData(){
        Profile objProfile = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User objUser = new User(Alias = 'standt', Email='standarduser@novartis.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = objProfile.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='standardusertest@novartis.com');
        insert objUser;
        //User_Infusion_Dates__c objUser_Infusion_Dates = TestDataFactory.createUser_InfusionDate(true);
        
        User_Infusion_Dates__c objUserInfusionDates  = new User_Infusion_Dates__c ();
        objUserInfusionDates.Name = 'Test user user infusion';
        objUserInfusionDates.OwnerId=objuser.Id;
        objUserInfusionDates.Status__c='Active';
        //objUserInfusionDates.Patient_Reference_ID__c='20220418003';
        objUserInfusionDates.Infusion_Date__c = system.today()+3;
        insert objUserInfusionDates;
        
        //Below Master configuration creation covers CalendarActivitiesTriggerhelper Coverage
        Id calendarrecordtypeid=Schema.SObjectType.Master_Configuration__c.getRecordTypeInfosByName().get('Calendar Activities').getRecordTypeId();
        Master_Configuration__c conf3=new Master_Configuration__c();
        conf3.Infusion_Center_Id__c='Test';
        conf3.Infusion_Center_Name__c='Test';
        conf3.Infusion_Center_Address__c='Test';
        conf3.Street__c='Test';
        conf3.State__c='Test';
        conf3.City__c='Test';
        conf3.Country__c='Test';
        conf3.PostalCode__c='123456';
        conf3.Active__c= true;
        conf3.Address_2__c='test';
        conf3.Address_1__c='test';   
        conf3.Address_3__c='test';
        conf3.Calendar_Activity__c='test';
        conf3.Calendar_Activity_desc__c='test';
        conf3.Calendar_Activity_duration__c='12';
        conf3.Calendar_Activity_Duration_Type__c='Day';
        conf3.Calendar_email_template__c='Infusion day';
        conf3.Description__c='test';
        conf3.Dosage__c= 2;
        conf3.End_Weight__c= 2;
        conf3.First_Notification__c='12';
        conf3.Institution_Id__c='test';
        conf3.Institution_Name__c='test';
        conf3.Link__c='www.salesforce.com';
        conf3.Weight_Range__c='1-2';
        conf3.Record_Status__c='t';
        conf3.Second_Notification__c='12';
        conf3.Spanish_Calendar_Activity__c='test';
        conf3.Spanish_Calendar_Activity_Description__c='test';
        conf3.Start_Weight__c= 2;
        conf3.Training_Name__c='test';
        conf3.Type__c='PDF';
        conf3.Vial5_5__c= 1;
        conf3.Vial8_3__c= 1;
        conf3.Viales_Totales__c= 1;
        conf3.RecordTypeId=calendarrecordtypeid;
        
        insert conf3;
        
        //Below UserCalendar  creation covers CalendarActivitiesTriggerhelper Coverage
        
        User_Calendar__c objUserCalendar = TestDataFactory.createUser_Calendar(false);
        objUserCalendar.Event_Type__c ='CALENDAR';
        objUserCalendar.Name='CALENDARTEST';
        objUserCalendar.Calendar_email_template__c = 'Pre infusion';
        objUserCalendar.First_Notification_Date__c = '2022-03-16 00:00:00';
        objUserCalendar.Second_Notification_Date__c = '2022-03-19 00:00:00';
        objUserCalendar.User_Infusion_Date_Id__c= objUserInfusionDates.Id;
        insert objUserCalendar ;
        
        
    }
    
    static testmethod void getUserCalendarEventsTest() {
        test.startTest();
        User_Infusion_Dates__c infusion=new User_Infusion_Dates__c();
        infusion=NewInfusionDateCntrl.saveInfuDate('Test',system.today());
        System.assertNotEquals(null, infusion,'Infusion Dates are not null');
        test.stopTest();
    }
    
    static testmethod void getPatientDetailsTest() {
        User objuser= [Select id from User where LastName='Testing' Limit 1]; 
        test.startTest();
        Map<String, String> mapIdNamePatientId = new Map<String, String>();    
        mapIdNamePatientId=NewInfusionDateCntrl.getPatientMap(objuser.Id);
        System.assertNotEquals(null, mapIdNamePatientId,'Patientid is not null');
        test.stopTest();
    }
    static testmethod void getPatientDetailsListTest() {
        User objuser= [Select id from User where LastName='Testing' Limit 1]; 
        User_Infusion_Dates__c objuserinfusion= [Select id from User_Infusion_Dates__c where Name='Test user user infusion' Limit 1]; 
        test.startTest();
        List<User_Infusion_Dates__c> lstInfusionDates = new List<User_Infusion_Dates__c>();    
        lstInfusionDates = NewInfusionDateCntrl.getPatientList(objuser.id,objuserinfusion.Id);
        System.assertNotEquals(null, lstInfusionDates,'Infusion dates is not null');
        test.stopTest();
    }
    static testmethod void getupdateInfuDateTest() {
        User objuser= [Select id from User where LastName='Testing' Limit 1]; 
        User_Infusion_Dates__c objuserinfusion= [Select id,Name,Infusion_Date__c,Patient_Reference_ID__c from User_Infusion_Dates__c where Name='Test user user infusion' Limit 1]; 
        test.startTest();
        List<User_Infusion_Dates__c> lstInfusionDate = new List<User_Infusion_Dates__c>();
        try{
            lstInfusionDate[0] = NewInfusionDateCntrl.updateInfuDate(objuserinfusion.Name,objuserinfusion.Infusion_Date__c,objuserinfusion.Patient_Reference_ID__c,objuserinfusion.Id);
        }catch(Exception e){
            
        }
        System.assertNotEquals(null, lstInfusionDate,'Infusion dates is not null for updation');
        test.stopTest();
    }
}